<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DestinationSeeder extends Seeder
{
    public function run(): void
    {

        $destinations = [

            // =============== SAMARINDA ===============
            [
                'created_by' => 1,
                'category_id' => 6,
                'place_name' => 'Kampung Budaya Pampang',
                'slug' => 'kampung-budaya-pampang',
                'description' => 'Desa adat Dayak Kenyah dengan rumah panjang, tarian gantar, dan upacara adat. Akses via speedboat Sungai Mahakam (±2 jam).',
                'administrative_area' => 'Samarinda Utara',
                'province' => 'Kalimantan Timur',
                'rating' => 4.6,
                'rating_count' => 320,
                'time_minutes' => 180,
                'best_visit_time' => 'pagi',
                'latitude' => -0.6322,
                'longitude' => 117.0856,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'created_by' => 1,
                'category_id' => 3,
                'place_name' => 'Air Terjun Tanah Merah',
                'slug' => 'air-terjun-tanah-merah',
                'description' => 'Air terjun alami dengan kolam alami di tengah hutan kota Samarinda.',
                'administrative_area' => 'Samarinda Ilir',
                'province' => 'Kalimantan Timur',
                'rating' => 4.3,
                'rating_count' => 145,
                'time_minutes' => 120,
                'best_visit_time' => 'siang',
                'latitude' => -0.5750,
                'longitude' => 117.1422,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'created_by' => 1,
                'category_id' => 7,
                'place_name' => 'Nasi Kuning Samarinda',
                'slug' => 'nasi-kuning-samarinda',
                'description' => 'Nasi kuning khas Samarinda disajikan dengan ikan asin, sambal terasi, dan telur. Tempat populer: Warung Nasi Kuning Bang Amin.',
                'administrative_area' => 'Samarinda Kota',
                'province' => 'Kalimantan Timur',
                'rating' => 4.7,
                'rating_count' => 210,
                'time_minutes' => 45,
                'best_visit_time' => 'pagi',
                'latitude' => -0.4928,
                'longitude' => 117.1436,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'created_by' => 2,
                'category_id' => 7,
                'place_name' => 'Amplang Khas Samarinda',
                'slug' => 'amplang-samarinda',
                'description' => 'Kerupuk ikan khas Kaltim yang renyah dan gurih. Bisa dibeli di pusat oleh-oleh seperti Amplang Zulaikha.',
                'administrative_area' => 'Samarinda Seberang',
                'province' => 'Kalimantan Timur',
                'rating' => 4.8,
                'rating_count' => 380,
                'time_minutes' => 30,
                'best_visit_time' => 'siang',
                'latitude' => -0.5300,
                'longitude' => 117.1500,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // =============== BALIKPAPAN ===============
            [
                'created_by' => 2,
                'category_id' => 1,
                'place_name' => 'Pantai Lamaru',
                'slug' => 'pantai-lamaru',
                'description' => 'Pantai pasir putih tenang dengan pohon kelapa dan sunset indah.',
                'administrative_area' => 'Balikpapan Timur',
                'province' => 'Kalimantan Timur',
                'rating' => 4.4,
                'rating_count' => 210,
                'time_minutes' => 150,
                'best_visit_time' => 'sore',
                'latitude' => -1.2750,
                'longitude' => 116.9289,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'created_by' => 2,
                'category_id' => 2,
                'place_name' => 'Hutan Lindung Sungai Wain',
                'slug' => 'hutan-lindung-sungai-wain',
                'description' => 'Kawasan konservasi dengan trek alam, rumah pohon, dan satwa liar seperti bekantan.',
                'administrative_area' => 'Balikpapan Utara',
                'province' => 'Kalimantan Timur',
                'rating' => 4.7,
                'rating_count' => 178,
                'time_minutes' => 180,
                'best_visit_time' => 'pagi',
                'latitude' => -1.1092,
                'longitude' => 116.8914,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'created_by' => 2,
                'category_id' => 7,
                'place_name' => 'Soto Banjar Balikpapan',
                'slug' => 'soto-banjar-balikpapan',
                'description' => 'Soto khas Banjar yang populer di Balikpapan dengan kuah kuning gurih dan perkedel.',
                'administrative_area' => 'Balikpapan Kota',
                'province' => 'Kalimantan Timur',
                'rating' => 4.6,
                'rating_count' => 190,
                'time_minutes' => 45,
                'best_visit_time' => 'pagi',
                'latitude' => -1.2379,
                'longitude' => 116.8527,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'created_by' => 3,
                'category_id' => 7,
                'place_name' => 'Ikan Patin Bakar Sungai Wain',
                'slug' => 'ikan-patin-bakar-sungai-wain',
                'description' => 'Ikan patin segar dari Sungai Mahakam dibakar dengan bumbu rempah khas Kaltim.',
                'administrative_area' => 'Balikpapan Utara',
                'province' => 'Kalimantan Timur',
                'rating' => 4.8,
                'rating_count' => 156,
                'time_minutes' => 60,
                'best_visit_time' => 'malam',
                'latitude' => -1.1100,
                'longitude' => 116.8900,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // =============== KUTAI KARTANEGARA (TENGGARONG) ===============
            [
                'created_by' => 3,
                'category_id' => 5,
                'place_name' => 'Museum Mulawarman',
                'slug' => 'museum-mulawarman',
                'description' => 'Istana Kesultanan Kutai Kartanegara dengan koleksi emas, keris, dan takhta kerajaan.',
                'administrative_area' => 'Tenggarong',
                'province' => 'Kalimantan Timur',
                'rating' => 4.8,
                'rating_count' => 265,
                'time_minutes' => 120,
                'best_visit_time' => 'siang',
                'latitude' => -0.4350,
                'longitude' => 117.0161,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'created_by' => 3,
                'category_id' => 3,
                'place_name' => 'Air Terjun Loa Janjang',
                'slug' => 'air-terjun-loa-janjang',
                'description' => 'Air terjun alami dengan kolam alami dan tebing curam di pinggiran Tenggarong.',
                'administrative_area' => 'Loa Janjang',
                'province' => 'Kalimantan Timur',
                'rating' => 4.5,
                'rating_count' => 98,
                'time_minutes' => 120,
                'best_visit_time' => 'pagi',
                'latitude' => -0.4800,
                'longitude' => 117.0400,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'created_by' => 3,
                'category_id' => 7,
                'place_name' => 'Pisang Gapit Khas Tenggarong',
                'slug' => 'pisang-gapit-tenggarong',
                'description' => 'Pisang bakar dijepit dengan saus gula merah atau keju, kuliner legendaris Tenggarong.',
                'administrative_area' => 'Tenggarong',
                'province' => 'Kalimantan Timur',
                'rating' => 4.5,
                'rating_count' => 132,
                'time_minutes' => 30,
                'best_visit_time' => 'malam',
                'latitude' => -0.4360,
                'longitude' => 117.0170,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // =============== KUTAI BARAT ===============
            [
                'created_by' => 4,
                'category_id' => 2,
                'place_name' => 'Tering Batu Bungan',
                'slug' => 'tering-batu-bungan',
                'description' => 'Formasi batu jamur alami di tepi Sungai Mahakam. Akses via speedboat dari Melak (±3 jam).',
                'administrative_area' => 'Tering',
                'province' => 'Kalimantan Timur',
                'rating' => 4.6,
                'rating_count' => 82,
                'time_minutes' => 240,
                'best_visit_time' => 'pagi',
                'latitude' => 0.5961,
                'longitude' => 115.7161,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'created_by' => 4,
                'category_id' => 6,
                'place_name' => 'Kampung Long Lunuk',
                'slug' => 'kampung-long-lunuk',
                'description' => 'Desa Dayak Tunjung dengan upacara adat dan arsitektur rumah panjang. Akses hanya lewat sungai.',
                'administrative_area' => 'Long Iram',
                'province' => 'Kalimantan Timur',
                'rating' => 4.4,
                'rating_count' => 63,
                'time_minutes' => 360,
                'best_visit_time' => 'pagi',
                'latitude' => 0.6631,
                'longitude' => 115.5122,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'created_by' => 4,
                'category_id' => 7,
                'place_name' => 'Manuk Kacang (Ayam Masak Kacang)',
                'slug' => 'manuk-kacang-kutai-barat',
                'description' => 'Masakan khas Dayak Tunjung: ayam dimasak dengan kacang tanah, daun singkong, dan rempah alami.',
                'administrative_area' => 'Melak',
                'province' => 'Kalimantan Timur',
                'rating' => 4.5,
                'rating_count' => 78,
                'time_minutes' => 60,
                'best_visit_time' => 'siang',
                'latitude' => 0.6000,
                'longitude' => 115.8000,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // =============== KUTAI TIMUR & BERAU ===============
            [
                'created_by' => 1,
                'category_id' => 1,
                'place_name' => 'Pulau Derawan',
                'slug' => 'pulau-derawan',
                'description' => 'Surga bawah laut dengan penyu, terumbu karang, dan air jernih. Akses via Tanjung Redeb.',
                'administrative_area' => 'Derawan',
                'province' => 'Kalimantan Timur',
                'rating' => 4.9,
                'rating_count' => 412,
                'time_minutes' => 480,
                'best_visit_time' => 'siang',
                'latitude' => 2.2917,
                'longitude' => 118.6500,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'created_by' => 1,
                'category_id' => 1,
                'place_name' => 'Pulau Maratua',
                'slug' => 'pulau-maratua',
                'description' => 'Pulau karang dengan laguna biru dan diving spot kelas dunia.',
                'administrative_area' => 'Maratua',
                'province' => 'Kalimantan Timur',
                'rating' => 4.8,
                'rating_count' => 287,
                'time_minutes' => 540,
                'best_visit_time' => 'pagi',
                'latitude' => 2.4136,
                'longitude' => 118.5750,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'created_by' => 1,
                'category_id' => 1,
                'place_name' => 'Pulau Sangalaki',
                'slug' => 'pulau-sangalaki',
                'description' => 'Situs konservasi penyu hijau dan spot snorkeling terbaik di Kaltim.',
                'administrative_area' => 'Berau',
                'province' => 'Kalimantan Timur',
                'rating' => 4.8,
                'rating_count' => 164,
                'time_minutes' => 500,
                'best_visit_time' => 'pagi',
                'latitude' => 2.2500,
                'longitude' => 118.5000,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'created_by' => 1,
                'category_id' => 7,
                'place_name' => 'Sate Payau Khas Berau',
                'slug' => 'sate-payau-berau',
                'description' => 'Sate daging rusa liar (payau) dengan bumbu kacang khas pesisir Berau. Rasanya gurih dan unik.',
                'administrative_area' => 'Tanjung Redeb',
                'province' => 'Kalimantan Timur',
                'rating' => 4.7,
                'rating_count' => 120,
                'time_minutes' => 60,
                'best_visit_time' => 'malam',
                'latitude' => 2.1333,
                'longitude' => 117.5167,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // =============== MAHAKAM ULU ===============
            [
                'created_by' => 2,
                'category_id' => 6,
                'place_name' => 'Kampung Datah Dian',
                'slug' => 'kampung-datah-dian',
                'description' => 'Desa Dayak Kenyah pedalaman dengan ukiran, tarian, dan upacara adat. Akses hanya lewat sungai (±8 jam dari Long Bagun).',
                'administrative_area' => 'Long Bagun',
                'province' => 'Kalimantan Timur',
                'rating' => 4.5,
                'rating_count' => 54,
                'time_minutes' => 480,
                'best_visit_time' => 'pagi',
                'latitude' => -0.4028,
                'longitude' => 114.7361,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'created_by' => 2,
                'category_id' => 2,
                'place_name' => 'Bukit Batu Bungan Hulu',
                'slug' => 'bukit-batu-bungan-hulu',
                'description' => 'Formasi batu karst di hulu Mahakam dengan pemandangan hutan perawan dan aliran sungai jernih.',
                'administrative_area' => 'Long Bagun',
                'province' => 'Kalimantan Timur',
                'rating' => 4.6,
                'rating_count' => 45,
                'time_minutes' => 300,
                'best_visit_time' => 'pagi',
                'latitude' => -0.3800,
                'longitude' => 114.7000,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'created_by' => 2,
                'category_id' => 7,
                'place_name' => 'Umaq Bawang (Sup Bawang Dayak)',
                'slug' => 'umaq-bawang-mahakam-uluh',
                'description' => 'Sup tradisional Dayak dari bawang hutan, ikan sungai, dan rempah alami.',
                'administrative_area' => 'Long Bagun',
                'province' => 'Kalimantan Timur',
                'rating' => 4.4,
                'rating_count' => 38,
                'time_minutes' => 60,
                'best_visit_time' => 'siang',
                'latitude' => -0.4000,
                'longitude' => 114.7300,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // =============== PASER ===============
            [
                'created_by' => 3,
                'category_id' => 2,
                'place_name' => 'Gunung Batu Bulan',
                'slug' => 'gunung-batu-bulan',
                'description' => 'Formasi batu karst raksasa dengan pemandangan lembah dan hutan tropis.',
                'administrative_area' => 'Tanah Grogot',
                'province' => 'Kalimantan Timur',
                'rating' => 4.4,
                'rating_count' => 76,
                'time_minutes' => 180,
                'best_visit_time' => 'pagi',
                'latitude' => -2.1100,
                'longitude' => 116.4561,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'created_by' => 3,
                'category_id' => 3,
                'place_name' => 'Air Terjun Bongbongan',
                'slug' => 'air-terjun-bongbongan',
                'description' => 'Air terjun bertingkat di hutan Paser dengan kolam alami dan udara sejuk.',
                'administrative_area' => 'Kuaro',
                'province' => 'Kalimantan Timur',
                'rating' => 4.5,
                'rating_count' => 62,
                'time_minutes' => 150,
                'best_visit_time' => 'siang',
                'latitude' => -1.8500,
                'longitude' => 116.3000,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'created_by' => 3,
                'category_id' => 7,
                'place_name' => 'Papeda & Ikan Kuah Kuning Paser',
                'slug' => 'papeda-ikan-kuah-kuning-paser',
                'description' => 'Papeda (bubur sagu) disajikan dengan ikan kuah kuning berempah khas Paser.',
                'administrative_area' => 'Tanah Grogot',
                'province' => 'Kalimantan Timur',
                'rating' => 4.6,
                'rating_count' => 95,
                'time_minutes' => 60,
                'best_visit_time' => 'siang',
                'latitude' => -2.1050,
                'longitude' => 116.4600,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // =============== BONTANG ===============
            [
                'created_by' => 4,
                'category_id' => 2,
                'place_name' => 'Taman Nasional Kutai',
                'slug' => 'taman-nasional-kutai',
                'description' => 'Hutan hujan tropis tertua di dunia, habitat orangutan, bekantan, dan rusa sambar.',
                'administrative_area' => 'Bontang',
                'province' => 'Kalimantan Timur',
                'rating' => 4.7,
                'rating_count' => 189,
                'time_minutes' => 240,
                'best_visit_time' => 'pagi',
                'latitude' => 0.7450,
                'longitude' => 117.3811,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'created_by' => 4,
                'category_id' => 1,
                'place_name' => 'Pantai Taman Bontang',
                'slug' => 'pantai-taman-bontang',
                'description' => 'Pantai buatan dengan fasilitas rekreasi keluarga dan pemandangan laut.',
                'administrative_area' => 'Bontang Selatan',
                'province' => 'Kalimantan Timur',
                'rating' => 4.2,
                'rating_count' => 110,
                'time_minutes' => 120,
                'best_visit_time' => 'sore',
                'latitude' => 0.1250,
                'longitude' => 117.4500,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'created_by' => 4,
                'category_id' => 7,
                'place_name' => 'Kue Apok Bontang',
                'slug' => 'kue-apok-bontang',
                'description' => 'Kue tradisional dari tepung beras dan gula merah, dibakar dalam pot tanah liat.',
                'administrative_area' => 'Bontang Utara',
                'province' => 'Kalimantan Timur',
                'rating' => 4.5,
                'rating_count' => 88,
                'time_minutes' => 45,
                'best_visit_time' => 'siang',
                'latitude' => 0.1400,
                'longitude' => 117.4600,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // =============== PENAJAM PASER UTARA & IKN ===============
            [
                'created_by' => 5,
                'category_id' => 1,
                'place_name' => 'Pantai Nenang',
                'slug' => 'pantai-nenang',
                'description' => 'Pantai berpasir putih dekat IKN, cocok untuk wisata alam dan fotografi.',
                'administrative_area' => 'Penajam',
                'province' => 'Kalimantan Timur',
                'rating' => 4.3,
                'rating_count' => 102,
                'time_minutes' => 150,
                'best_visit_time' => 'sore',
                'latitude' => -1.4028,
                'longitude' => 116.7361,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'created_by' => 5,
                'category_id' => 2,
                'place_name' => 'Hutan Lindung IKN (Bukit Soeharto)',
                'slug' => 'hutan-lindung-ikn-bukit-soeharto',
                'description' => 'Kawasan hutan lindung di sekitar IKN dengan trek alam dan keanekaragaman hayati tinggi.',
                'administrative_area' => 'Sepaku',
                'province' => 'Kalimantan Timur',
                'rating' => 4.5,
                'rating_count' => 76,
                'time_minutes' => 180,
                'best_visit_time' => 'pagi',
                'latitude' => -1.2200,
                'longitude' => 116.8000,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'created_by' => 5,
                'category_id' => 7,
                'place_name' => 'Kuliner Warung IKN (Nasi Ikan Bakar)',
                'slug' => 'nasi-ikan-bakar-ikn',
                'description' => 'Nasi dengan ikan sungai bakar, sambal dabai, dan lalapan segar di warung pinggir jalan dekat IKN.',
                'administrative_area' => 'Sepaku',
                'province' => 'Kalimantan Timur',
                'rating' => 4.6,
                'rating_count' => 92,
                'time_minutes' => 60,
                'best_visit_time' => 'malam',
                'latitude' => -1.2250,
                'longitude' => 116.8100,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // =============== TAMBAHAN: DESTINASI & KULINER LAINNYA ===============
            [
                'created_by' => 1,
                'category_id' => 4,
                'place_name' => 'Taman Rekreasi Lempake',
                'slug' => 'taman-rekreasi-lempake',
                'description' => 'Taman keluarga dengan danau buatan, perahu, dan area piknik di Samarinda.',
                'administrative_area' => 'Samarinda Utara',
                'province' => 'Kalimantan Timur',
                'rating' => 4.2,
                'rating_count' => 165,
                'time_minutes' => 150,
                'best_visit_time' => 'sore',
                'latitude' => -0.5500,
                'longitude' => 117.1700,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'created_by' => 2,
                'category_id' => 7,
                'place_name' => 'Sambal Dabai',
                'slug' => 'sambal-dabai',
                'description' => 'Sambal khas Kaltim dari buah dabai (buah lokal berwarna ungu) yang langka dan bergizi tinggi.',
                'administrative_area' => 'Samarinda',
                'province' => 'Kalimantan Timur',
                'rating' => 4.7,
                'rating_count' => 210,
                'time_minutes' => 30,
                'best_visit_time' => 'siang',
                'latitude' => -0.5000,
                'longitude' => 117.1500,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'created_by' => 3,
                'category_id' => 1,
                'place_name' => 'Pantai Babi',
                'slug' => 'pantai-babi-berau',
                'description' => 'Pantai tersembunyi di Berau dengan pasir putih dan air biru jernih. Akses via speedboat.',
                'administrative_area' => 'Pulau Maratua',
                'province' => 'Kalimantan Timur',
                'rating' => 4.9,
                'rating_count' => 89,
                'time_minutes' => 180,
                'best_visit_time' => 'pagi',
                'latitude' => 2.4200,
                'longitude' => 118.5800,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'created_by' => 4,
                'category_id' => 7,
                'place_name' => 'Bubur Pedas Samarinda',
                'slug' => 'bubur-pedas-samarinda',
                'description' => 'Bubur gurih dengan 10+ sayuran dan rempah, disajikan saat acara adat atau Ramadan.',
                'administrative_area' => 'Samarinda Ilir',
                'province' => 'Kalimantan Timur',
                'rating' => 4.6,
                'rating_count' => 176,
                'time_minutes' => 60,
                'best_visit_time' => 'pagi',
                'latitude' => -0.5800,
                'longitude' => 117.1400,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'created_by' => 5,
                'category_id' => 5,
                'place_name' => 'Benteng Kutai Lama',
                'slug' => 'benteng-kutai-lama',
                'description' => 'Situs sejarah bekas pusat Kesultanan Kutai Kartanegara di muara Sungai Mahakam.',
                'administrative_area' => 'Muara Kaman',
                'province' => 'Kalimantan Timur',
                'rating' => 4.3,
                'rating_count' => 68,
                'time_minutes' => 120,
                'best_visit_time' => 'pagi',
                'latitude' => -0.9500,
                'longitude' => 117.0500,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'created_by' => 5,
                'category_id' => 7,
                'place_name' => 'Kue Cucur Paser',
                'slug' => 'kue-cucur-paser',
                'description' => 'Kue tradisional manis dari gula merah dan tepung beras, mirip serabi tapi lebih tebal.',
                'administrative_area' => 'Pasir Belengkong',
                'province' => 'Kalimantan Timur',
                'rating' => 4.4,
                'rating_count' => 72,
                'time_minutes' => 30,
                'best_visit_time' => 'siang',
                'latitude' => -2.1200,
                'longitude' => 116.4700,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'created_by' => 1,
                'category_id' => 2,
                'place_name' => 'Gua Teletubbies (Kutai Timur)',
                'slug' => 'gua-teletubbies-kutim',
                'description' => 'Formasi batu kapur unik menyerupai bukit-bukit Teletubbies di Sangatta.',
                'administrative_area' => 'Sangatta',
                'province' => 'Kalimantan Timur',
                'rating' => 4.5,
                'rating_count' => 104,
                'time_minutes' => 120,
                'best_visit_time' => 'pagi',
                'latitude' => 0.9200,
                'longitude' => 117.5000,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'created_by' => 2,
                'category_id' => 7,
                'place_name' => 'Kue Lupis Balikpapan',
                'slug' => 'kue-lupis-balikpapan',
                'description' => 'Kue ketan dibalut kelapa parut dan disiram gula merah cair.',
                'administrative_area' => 'Balikpapan Barat',
                'province' => 'Kalimantan Timur',
                'rating' => 4.5,
                'rating_count' => 98,
                'time_minutes' => 30,
                'best_visit_time' => 'siang',
                'latitude' => -1.2500,
                'longitude' => 116.8400,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

        ];

        DB::table('destinations')->insert($destinations);
    }
}